version: "3.9"

services:
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: algobank
            POSTGRES_PASSWORD: algobank
            POSTGRES_DB: algobank
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"

    backend:
        build:
            context: ./backend
        env_file:
            - backend/.env
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: algobank
            POSTGRES_PASSWORD: algobank
            POSTGRES_DB: algobank
            REDIS_URL: redis://redis:6379
        depends_on:
            - postgres
            - redis
        ports:
            - "4000:4000"

volumes:
    postgres_data:
